export const PaymentMethodEnabled = {
  PAYMENT_RMS_CREDIT_CARD_ENABLED: 'PAYMENT_RMS_CREDIT_CARD_ENABLED',
  PAYMENT_SQUARE_CREDIT_CARD_ENABLED: 'PAYMENT_SQUARE_CREDIT_CARD_ENABLED',
  PAYMENT_STRIPE_CREDIT_CARD_ENABLED: 'PAYMENT_STRIPE_CREDIT_CARD_ENABLED',
  PAYMENT_TRUSTPAYMENTS_CREDIT_CARD_ENABLED: 'PAYMENT_TRUSTPAYMENTS_CREDIT_CARD_ENABLED',
  PAYMENT_VIVA_CREDIT_CARD_ENABLED: 'PAYMENT_VIVA_CREDIT_CARD_ENABLED',
  PAYMENT_PAYABL_CREDIT_CARD_ENABLED: 'PAYMENT_PAYABL_CREDIT_CARD_ENABLED',
  PAYMENT_GLOBAL_PAY_CREDIT_CARD_ENABLED: 'PAYMENT_GLOBAL_PAY_CREDIT_CARD_ENABLED',
  PAYMENT_PAYMENTSENSE_CREDIT_CARD_ENABLED: 'PAYMENT_PAYMENTSENSE_CREDIT_CARD_ENABLED',
  PAYMENT_JCC_CREDIT_CARD_ENABLED: 'PAYMENT_JCC_CREDIT_CARD_ENABLED',
  PAYMENT_MOLLIE_CREDIT_CARD_ENABLED: 'PAYMENT_MOLLIE_CREDIT_CARD_ENABLED',
  PAYMENT_FYGARO_CREDIT_CARD_ENABLED: 'PAYMENT_FYGARO_CREDIT_CARD_ENABLED',
  PAYMENT_APCOPAY_CREDIT_CARD_ENABLED: 'PAYMENT_APCOPAY_CREDIT_CARD_ENABLED'

};
